repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

{{- $istioNamespace := "istio-system" }}

releases:
  - name: namespaces-systems
    chart: ./chart-libs/namespaces
    version: v0.1.0
    values:
      - namespaces:
        - name: cert-manager
        - name: {{ $istioNamespace }}

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    forceNamespace: cert-manager
    version: v1.14.5
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.crds.yaml
    values:
      - installCRDs: false
        logLevel: 6

  - name: istio-certificates
    chart: ./chart-libs/istio-certificates
    namespace: {{ $istioNamespace }}
    forceNamespace: {{ $istioNamespace }}
    version: v0.1.0

  - name: istio-csr
    chart: jetstack/cert-manager-istio-csr
    namespace: {{ $istioNamespace }}
    forceNamespace: {{ $istioNamespace }}
    version: v0.8.1

  - name: istio-base
    chart: istio/base
    namespace: {{ $istioNamespace }}
    forceNamespace: {{ $istioNamespace }}
    version: v1.22.0
    values:
      - defaultRevision: default

  - name: istiod
    chart: istio/istiod
    namespace: {{ $istioNamespace }}
    forceNamespace: {{ $istioNamespace }}
    version: v1.22.0
