{{- range .Values.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    {{- range $label, $value := .labels }}
    {{ $label }}: {{ $value }}
    {{- end }}
{{- end }}
